name: Run npm tbuild on manual trigger

on:
  workflow_dispatch:
    inputs:
      run-tests:
        description: 'Run npm build'
        required: true
        default: 'true'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js and npm
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      working-directory: apps/login

    - name: Run npm test
      run: npm run build
      working-directory: apps/login
      # if: github.event.inputs.run-tests == 'true'
