name: Deploy Web

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js and npm
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      working-directory: apps/web

    - name: Run build
      run: npm run build
      working-directory: apps/web

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.NDENO_DEV_REGION}}
        
    - name: Deploy static site to S3 bucket
      run: aws s3 sync /dist s3://${{ secrets.NDENO_STATIC_BUCKET}}
